[package]
name = "kubos-file-client"
version = "0.1.0"
authors = ["Ryan Plauche <ryan@kubos.co>"]
edition = "2018"

[dependencies]
simplelog = "^0.12.0"
clap = "4.5"
log = "^0.4.0"
file-protocol = { path = "libs/file-protocol" }
failure = "0.1.2"
#rustbar = "0.2.0"


